export const StatusKeys = {
  NEW: 'NEW',
  ESTIMATED: 'ESTIMATED',
  APPROVED: 'APPROVED',
  BIDS: 'BIDS',
  ASSIGNED: 'ASSIGNED',
  DISPATCHED: 'DISPATCHED',
  ACCEPTED: 'ACCEPTED',
  INPROGRESS: 'INPROGRESS',
  ONHOLD: 'ONHOLD',
  COMPLETED: 'COMPLETED',
  INVOICED: 'INVOICED',
  PAID: 'PAID',
};
